"""
Launch polish: site-wide worn-vintage theme (CSS + JS), logo/favicon,
search verification.

Provides functions for the ``--polish`` and ``--verify-search`` CLI flags
in :mod:`sync.sync_wiki`.

The wiki wears the same "1999 worn unsleeved vintage TCG" aesthetic as the
game client (lobby / deck builder / cards): Alegreya SC + Alegreya type,
parchment-and-gold on a candlelit brown table. All palette values are taken
verbatim from ``src/grid_tactics/server/static/game.css`` (.lobby2 /
#screen-deck-builder / .cf2 token blocks) so the wiki and the app read as
one product.

Usage::

    from sync.sync_polish import push_vintage_theme, push_vintage_common_js
    from sync.sync_polish import upload_logo, upload_favicon, verify_search
    from sync.client import get_site

    site = get_site()
    push_vintage_theme(site)      # MediaWiki:Common.css (wholesale replace)
    push_vintage_common_js(site)  # MediaWiki:Common.js  (wholesale replace)
    upload_logo(site)
    upload_favicon(site)
    verify_search(site)
"""

from __future__ import annotations

import struct
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# MediaWiki:Common.css — composed wholesale
# ---------------------------------------------------------------------------
#
# Historically Common.css accumulated append-only marker blocks (Montserrat
# fonts, dark search, cyan HUD theme, mobile, logo, hero search). The re-skin
# REPLACES the whole page with one composed stylesheet: stale blocks vanish
# in a single edit and the page is content-idempotent afterwards.

_COMMON_CSS_HEADER = (
    "/* === Grid Tactics Worn-Vintage Theme ===================================\n"
    "   Generated by wiki/sync/sync_polish.py (push_vintage_theme) — do NOT\n"
    "   hand-edit; changes here are overwritten by the next --polish run.\n"
    "   Palette + type mirror the game client (game.css .lobby2 / .cf2).\n"
    "   ===================================================================== */"
)

_VINTAGE_THEME_CSS = """\
/* --- Tokens (verbatim from the game client) ------------------------ */
:root {
  --gtv-parch:      #f2ead2;   /* brightest text / titles            */
  --gtv-parch-dim:  #cbb98f;   /* default body text                  */
  --gtv-parch-mute: #9a865c;   /* muted labels, secondary            */
  --gtv-gold:       #e0a23c;   /* accent, links, focus               */
  --gtv-gold-lt:    #ffd873;   /* hover, primary button top          */
  --gtv-bronze:     #6b5730;   /* medium borders                     */
  --gtv-bronze-dk:  #3a2e18;   /* subtle borders                     */
  --gtv-field:      #191207;   /* input / row fill                   */
  --gtv-field-hi:   #221809;   /* row hover fill                     */
  --gtv-line:       #2c2113;   /* dividers                           */
  --gtv-rust:       #b5623a;   /* warm danger / red links            */
  --gtv-ink:        #241c10;   /* dark ink on parchment surfaces     */
  --gtv-ivory:      #e8dcbb;   /* aged card stock                    */
  --gtv-display: 'Alegreya SC', Georgia, serif;
  --gtv-body:    'Alegreya', Georgia, serif;
}

/* Re-point the Citizen/Codex palette at the vintage tokens so every skin
   component (sticky TOC, buttons, tabs, progress accents) follows suit. */
:root, .skin-citizen, .skin-theme-clientpref-night, .skin-theme-clientpref-os {
  --color-progressive: #e0a23c !important;
  --color-progressive--hover: #ffd873 !important;
  --color-progressive--focus: #ffd873 !important;
  --color-progressive--active: #e0a23c !important;
  --color-link: #e0a23c !important;
  --color-link--hover: #ffd873 !important;
  --color-link--active: #ffd873 !important;
  --color-link--visited: #e0a23c !important;
  --color-link-red: #b5623a !important;
  --color-link-red--visited: #b5623a !important;
}

/* Citizen sticky TOC links (Codex fake-buttons, not plain anchors) */
.citizen-toc-link, a.citizen-toc-link {
  color: var(--gtv-parch-dim) !important;
  font-family: var(--gtv-body);
}
.citizen-toc-link:hover, .citizen-toc-link.citizen-toc-link-active {
  color: var(--gtv-gold-lt) !important;
}
.citizen-toc-top { color: var(--gtv-parch-mute) !important; }

/* --- Candlelit table backdrop (same recipe as the lobby) ----------- */
html, body {
  background: #160f07 !important;
  color: var(--gtv-parch-dim);
}
body {
  font-family: var(--gtv-body);
  position: relative;
  background:
    radial-gradient(120% 120% at 22% 4%,   rgba(224, 162, 60, 0.14) 0%, transparent 46%),
    radial-gradient(135% 130% at 82% 104%, rgba(120, 60, 130, 0.10) 0%, transparent 52%),
    radial-gradient(150% 150% at 50% 38%,  #251a0e 0%, #160f07 56%, #0b0805 100%) !important;
  background-attachment: fixed !important;
}
/* Vignette so the corners sink into shadow like a card frame. */
body::before {
  content: '';
  position: fixed;
  inset: 0;
  pointer-events: none;
  z-index: 0;
  background: radial-gradient(120% 120% at 40% 30%, transparent 55%, rgba(0, 0, 0, 0.5) 100%);
}
/* Keep content above the vignette */
#mw-content, .citizen-body, #content, .mw-body { position: relative; z-index: 1; }

/* --- Typography ----------------------------------------------------- */
h1, h2, h3, h4, h5, h6,
.mw-first-heading, .mw-page-title-main,
.firstHeading, .mw-heading {
  font-family: var(--gtv-display) !important;
  color: var(--gtv-parch) !important;
  letter-spacing: 0.02em !important;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.8);
}

/* Page title: gold gradient rule beneath, like the lobby wordmark */
.mw-page-title, .mw-page-title-main, .firstHeading, h1.mw-first-heading {
  position: relative;
  padding-bottom: 12px;
  font-weight: 800 !important;
  font-size: clamp(30px, 3.6vw, 46px) !important;
  line-height: 1.02 !important;
  text-shadow: 0 2px 14px #000, 0 0 30px rgba(224, 162, 60, 0.18);
}
.mw-page-title::after, h1.mw-first-heading::after {
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  width: 96px;
  height: 3px;
  background: linear-gradient(90deg, var(--gtv-gold), transparent);
}

/* Section headings: gold left edge on a dark field, like lobby nav rows */
.mw-parser-output h2,
.mw-parser-output .mw-heading2 {
  position: relative;
  padding: 6px 12px 6px 14px !important;
  margin-top: 30px !important;
  border-left: 3px solid var(--gtv-gold) !important;
  border-bottom: 1px solid var(--gtv-line) !important;
  background: rgba(30, 22, 10, 0.55);
  border-radius: 0 6px 0 0;
  font-size: 22px !important;
  font-weight: 700 !important;
}
.mw-parser-output h3,
.mw-parser-output .mw-heading3 {
  padding: 4px 0 !important;
  margin-top: 22px !important;
  border-bottom: 1px solid var(--gtv-line) !important;
  font-size: 18px !important;
  font-weight: 700 !important;
  color: var(--gtv-parch) !important;
}

/* Tagline / "From Grid Tactics Wiki" subtitle under the page title */
.page-header__sub, .mw-page-description, .citizen-tagline,
.citizen-body .mw-body-header .mw-body-header-description {
  font-family: var(--gtv-display) !important;
  font-size: 12px !important;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--gtv-parch-mute) !important;
}

/* --- Links ----------------------------------------------------------- */
a, a:visited {
  color: var(--gtv-gold);
  text-decoration: none;
  transition: color 140ms ease;
}
a:hover {
  color: var(--gtv-gold-lt);
  text-shadow: 0 0 8px rgba(224, 162, 60, 0.35);
}
a.new, a.new:visited { color: var(--gtv-rust); }  /* red links go rust */
a:focus-visible, button:focus-visible, input:focus-visible {
  outline: 2px solid var(--gtv-gold-lt);
  outline-offset: 2px;
}

/* --- Body content surfaces ------------------------------------------ */
.mw-body, #mw-content, #content, .citizen-page-container,
.citizen-content-container {
  background: transparent !important;
}
.mw-body-content p,
.mw-parser-output p,
.mw-parser-output li,
.mw-parser-output dd {
  line-height: 1.6;
  color: var(--gtv-parch-dim);
  font-family: var(--gtv-body);
  font-size: 16px;
}
.mw-parser-output ul, .mw-parser-output ol {
  padding-left: 22px;
}
.mw-parser-output strong, .mw-parser-output b {
  color: var(--gtv-parch);
}
hr {
  border: 0;
  border-top: 1px solid var(--gtv-line);
}

/* --- Tables (wikitable + SMW results) -------------------------------- */
table.wikitable,
table.smwtable,
table.smwtable-clean,
.smw-table {
  background: rgba(20, 14, 6, 0.72) !important;
  border: 1px solid var(--gtv-bronze-dk) !important;
  border-collapse: separate !important;
  border-spacing: 0 !important;
  border-radius: 6px;
  color: var(--gtv-parch-dim) !important;
  font-family: var(--gtv-body);
  font-size: 14.5px;
}
table.wikitable th,
table.smwtable th,
table.smwtable-clean th {
  background: linear-gradient(180deg, rgba(224, 162, 60, 0.14), rgba(224, 162, 60, 0.03)) !important;
  color: var(--gtv-parch) !important;
  border-bottom: 1px solid var(--gtv-bronze) !important;
  border-right: 1px solid var(--gtv-bronze-dk) !important;
  font-family: var(--gtv-display) !important;
  font-weight: 700 !important;
  font-size: 12.5px !important;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  padding: 8px 12px !important;
  text-align: left !important;
}
table.wikitable td,
table.smwtable td,
table.smwtable-clean td {
  border: 1px solid rgba(58, 46, 24, 0.55) !important;
  padding: 7px 12px !important;
  background: transparent !important;
}
table.wikitable tr:hover td,
table.smwtable tr:hover td {
  background: var(--gtv-field-hi) !important;
}
table.wikitable tr:nth-child(even) td {
  background: rgba(224, 162, 60, 0.03) !important;
}

/* --- Infobox (manually-maintained pages) ----------------------------- */
/* Card pages carry their own inline parchment frame (Template:Card);
   this covers generic infoboxes with the deck builder's dark cardboard. */
.infobox:not(.gt-card), table.infobox:not(.gt-card) {
  background:
    radial-gradient(rgba(255, 240, 200, 0.03) 1px, transparent 1.6px),
    linear-gradient(160deg, #1a1409 0%, #140f07 60%, #0b0805 100%) !important;
  background-size: 5px 5px, 100% 100% !important;
  border: 1px solid var(--gtv-bronze) !important;
  border-radius: 8px !important;
  box-shadow: inset 0 0 24px rgba(0, 0, 0, 0.55),
              inset 0 1px 0 rgba(224, 162, 60, 0.05),
              0 10px 28px -14px rgba(0, 0, 0, 0.7);
}
.infobox:not(.gt-card) th,
.infobox:not(.gt-card) caption {
  color: var(--gtv-parch);
  font-family: var(--gtv-display);
  letter-spacing: 0.08em;
  text-transform: uppercase;
  font-size: 12px;
  padding: 8px 12px;
  background: rgba(224, 162, 60, 0.07);
  border-bottom: 1px solid var(--gtv-bronze-dk);
}
.infobox:not(.gt-card) td {
  color: var(--gtv-parch-dim);
  font-family: var(--gtv-body);
  font-size: 14px;
  padding: 8px 12px;
}

/* --- Links inside the parchment card frame --------------------------- */
/* Gold on ivory fails contrast — use bronze ink instead. */
.gt-card a, .gt-card a:visited,
.gt-cotd a, .gt-cotd a:visited {
  color: #7a5a1c !important;
  font-weight: 700;
}
.gt-card a:hover, .gt-cotd a:hover {
  color: #4a3208 !important;
  text-shadow: none;
}

/* --- Table of contents (core + Citizen) ------------------------------ */
.toc, .toccolours, .mw-toc, .toc-container,
.citizen-toc, .citizen-toc__list,
#toc, #toc > ul {
  background:
    radial-gradient(rgba(255, 240, 200, 0.03) 1px, transparent 1.6px),
    linear-gradient(160deg, #1a1409 0%, #140f07 60%, #0b0805 100%) !important;
  background-size: 5px 5px, 100% 100% !important;
  border: 1px solid var(--gtv-bronze-dk) !important;
  border-radius: 8px !important;
  padding: 12px 14px !important;
  font-family: var(--gtv-body);
}
.toctitle h2, .toc .toctitle,
.citizen-toc__list-title {
  font-family: var(--gtv-display) !important;
  font-size: 12px !important;
  letter-spacing: 0.14em !important;
  color: var(--gtv-parch-mute) !important;
  text-transform: uppercase !important;
  border-bottom: 1px solid var(--gtv-line);
  padding-bottom: 6px;
  margin-bottom: 8px !important;
}
.toc ul, .citizen-toc ul { padding-left: 16px; }
.toc a, .citizen-toc a {
  color: var(--gtv-parch-dim);
  font-size: 14px;
  line-height: 1.8;
  transition: color 140ms ease, padding-left 140ms ease;
}
.toc a:hover, .citizen-toc a:hover {
  color: var(--gtv-gold-lt);
  padding-left: 3px;
}

/* --- Citizen skin chrome --------------------------------------------- */
.citizen-drawer,
.citizen-drawer__list,
.citizen-sidebar,
.citizen-page-sidebar {
  background: rgba(14, 10, 4, 0.94) !important;
  border-right: 1px solid var(--gtv-bronze-dk) !important;
}
.citizen-drawer__item a,
.citizen-sidebar a { color: var(--gtv-parch-dim); }
.citizen-drawer__item a:hover,
.citizen-sidebar a:hover {
  color: var(--gtv-gold-lt);
  background: rgba(224, 162, 60, 0.06);
}

/* Top page-tools row (View source / History / Discussion / ...) */
.page-actions, .citizen-page-header__tools,
.citizen-header, .mw-body-header {
  border-bottom: 1px solid var(--gtv-line);
}
.citizen-menu__card a,
.mw-portlet a.cdx-button,
.page-actions a,
.vector-menu-heading {
  font-family: var(--gtv-display) !important;
  font-size: 12px !important;
  letter-spacing: 0.08em !important;
  text-transform: uppercase;
}

/* --- Footer ----------------------------------------------------------- */
.citizen-footer,
#footer, .mw-footer,
.footer {
  background: linear-gradient(180deg, rgba(224, 162, 60, 0.05), transparent) !important;
  border-top: 1px solid var(--gtv-bronze-dk) !important;
  color: var(--gtv-parch-mute) !important;
  font-family: var(--gtv-body);
  font-size: 13px;
  padding: 24px 24px 32px !important;
  margin-top: 48px;
}
.citizen-footer h3,
.citizen-footer .citizen-footer__sitetitle,
#footer strong, .mw-footer strong {
  font-family: var(--gtv-display) !important;
  color: var(--gtv-parch) !important;
  letter-spacing: 0.1em !important;
}
.citizen-footer a, #footer a { color: var(--gtv-gold); }

/* --- Code / pre / kbd -------------------------------------------------- */
code, pre, kbd, tt, samp {
  font-family: Consolas, 'JetBrains Mono', monospace !important;
  background: var(--gtv-field) !important;
  color: var(--gtv-parch-dim) !important;
  border: 1px solid var(--gtv-bronze-dk);
  padding: 2px 6px;
  border-radius: 4px;
}
pre {
  padding: 12px 14px;
  line-height: 1.5;
}

/* --- Search page -------------------------------------------------------- */
.mw-search-profile-tabs,
.search-types,
fieldset#mw-searchoptions {
  background: var(--gtv-field) !important;
  border-color: var(--gtv-bronze-dk) !important;
  color: var(--gtv-parch-dim) !important;
}
fieldset#mw-searchoptions legend { color: var(--gtv-parch-mute) !important; }
fieldset#mw-searchoptions label { color: var(--gtv-parch-dim) !important; }
.mw-search-profile-tabs a { color: var(--gtv-gold) !important; }
#searchText, .mw-searchInput, input[type="search"] {
  background: var(--gtv-field) !important;
  color: var(--gtv-parch) !important;
  border-color: var(--gtv-bronze) !important;
  font-family: var(--gtv-body);
}
.mw-search-results li, .searchresults { color: var(--gtv-parch-dim); }
.searchresult { color: var(--gtv-parch-dim) !important; }
.mw-search-result-data { color: var(--gtv-parch-mute) !important; }

/* --- Edit-source textarea ------------------------------------------------ */
textarea#wpTextbox1 {
  background: var(--gtv-field) !important;
  color: var(--gtv-parch-dim) !important;
  border: 1px solid var(--gtv-bronze) !important;
  font-family: Consolas, 'JetBrains Mono', monospace !important;
  font-size: 13px;
  line-height: 1.55;
  padding: 12px;
}

/* --- Selection highlight -------------------------------------------------- */
::selection { background: rgba(224, 162, 60, 0.4); color: #fff8e8; }
"""

_HERO_SEARCH_CSS = """\
/* --- Hero search bar (injected by Common.js) ----------------------------- */
#gt-hero-search {
  text-align: center;
  margin: 0 auto;
  max-width: 560px;
  padding: 1em 1em 0.5em;
  width: 100%;
  box-sizing: border-box;
}

#gt-hero-search form {
  display: flex;
  gap: 0;
}

#gt-hero-search input[type="search"] {
  flex: 1;
  padding: 0.75em 1.1em;
  font-size: 1rem;
  background: var(--gtv-field) !important;
  color: var(--gtv-parch) !important;
  border: 1px solid var(--gtv-bronze) !important;
  border-right: none !important;
  border-radius: 8px 0 0 8px !important;
  outline: none !important;
  box-shadow: none !important;
  transition: border-color 0.2s, box-shadow 0.2s;
  font-family: var(--gtv-body);
}

#gt-hero-search input[type="search"]:focus {
  border-color: var(--gtv-gold) !important;
  box-shadow: 0 0 0 2px rgba(224, 162, 60, 0.22) !important;
}

#gt-hero-search input[type="search"]::placeholder {
  color: #6a5a3a !important;
}

#gt-hero-search button[type="submit"] {
  padding: 0.75em 1.4em;
  background: linear-gradient(180deg, var(--gtv-gold-lt), var(--gtv-gold)) !important;
  color: #2a1c07 !important;
  border: none !important;
  border-radius: 0 8px 8px 0 !important;
  font-weight: 700;
  font-size: 0.95rem;
  cursor: pointer;
  font-family: var(--gtv-display);
  letter-spacing: 0.06em;
  text-shadow: 0 1px 0 rgba(255, 240, 200, 0.4);
  box-shadow: 0 4px 16px -4px rgba(224, 162, 60, 0.6),
              inset 0 1px 0 rgba(255, 255, 255, 0.45);
  transition: filter 0.2s;
}

#gt-hero-search button[type="submit"]:hover {
  filter: brightness(1.06);
}
"""

_MOBILE_CSS = """\
/* --- Mobile responsive ---------------------------------------------------- */
@media (max-width: 720px) {
  /* Card infobox: full width, no float on mobile */
  .gt-card, .infobox, .card-infobox {
    width: 100% !important;
    max-width: 100% !important;
    float: none !important;
    margin: 0 0 1em 0 !important;
  }

  /* Card art: scale to container */
  .gt-card img {
    max-width: 100% !important;
    height: auto !important;
  }

  /* SMW result tables: horizontal scroll */
  .smw-table-result, .wikitable {
    overflow-x: auto;
    display: block;
  }

  /* Body content padding */
  .mw-body-content, #mw-content-text {
    padding: 0.5em;
  }

  /* Hide sidebar on mobile */
  .mw-sidebar, #mw-panel, .citizen-drawer {
    display: none !important;
  }

  /* Card art responsive */
  .card-art img, .infobox img {
    max-width: 100%;
    height: auto;
  }

  /* Content area full width */
  .mw-body {
    margin-left: 0 !important;
  }

  /* Section headings trim */
  .mw-parser-output h2,
  .mw-parser-output .mw-heading2 { font-size: 18px !important; }
  table.wikitable, table.smwtable { font-size: 12.5px; }
}
"""

_LOGO_CSS = """\
/* --- Logo override --------------------------------------------------------- */
.citizen-header__logo img,
.mw-logo-icon {
  background-image: url('/w/images/Wiki.png') !important;
  background-size: contain;
  width: 50px;
  height: 50px;
}
.mw-wiki-logo {
  background-image: url('/w/images/Wiki.png') !important;
  background-size: contain;
}
"""

COMPOSED_COMMON_CSS = "\n\n".join([
    _COMMON_CSS_HEADER,
    _VINTAGE_THEME_CSS,
    _HERO_SEARCH_CSS,
    _MOBILE_CSS,
    _LOGO_CSS,
]).rstrip() + "\n"


def push_vintage_theme(site, dry_run: bool = False) -> str:
    """Replace MediaWiki:Common.css wholesale with the vintage theme.

    Unlike the old marker-append helpers, this REPLACES the entire page —
    the composed stylesheet is the single source of truth, so any legacy
    HUD/dark-search/hero blocks disappear in one edit. Idempotent by
    content comparison.

    Returns ``"created"``, ``"updated"``, or ``"unchanged"``.
    """
    page = site.pages["MediaWiki:Common.css"]
    current = page.text() if page.exists else ""

    if current.rstrip() == COMPOSED_COMMON_CSS.rstrip():
        print("  MediaWiki:Common.css: unchanged (vintage theme current)")
        return "unchanged"

    if dry_run:
        verb = "would-update" if page.exists else "would-create"
        print(f"  MediaWiki:Common.css: {verb} (vintage theme, wholesale)")
        return verb

    page.edit(
        COMPOSED_COMMON_CSS,
        summary="re-skin wiki to worn-vintage theme (matches game client)",
    )
    verb = "updated" if current else "created"
    print(f"  MediaWiki:Common.css: {verb} (vintage theme, wholesale)")
    return verb


# ---------------------------------------------------------------------------
# MediaWiki:Common.js — composed wholesale
# ---------------------------------------------------------------------------
#
# Three jobs: (1) inject the Google Fonts <link> for Alegreya + Alegreya SC
# (ResourceLoader silently drops @import from Common.css, so CSS can't do it),
# (2) inject the favicon <link>, (3) build the hero search bar on every page.

COMPOSED_COMMON_JS = """\
/* === Grid Tactics Common.js ==============================================
   Generated by wiki/sync/sync_polish.py (push_vintage_common_js) — do NOT
   hand-edit; changes here are overwritten by the next --polish run.
   ======================================================================= */

/* Worn-vintage fonts: Alegreya (body) + Alegreya SC (display) */
(function gtVintageFonts() {
  if (document.getElementById('gt-vintage-fonts')) return;
  var link = document.createElement('link');
  link.id = 'gt-vintage-fonts';
  link.rel = 'stylesheet';
  link.href = 'https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400;0,500;0,700;1,400&family=Alegreya+SC:wght@500;700;800&display=swap';
  document.head.appendChild(link);
})();

/* Favicon */
(function gtFavicon() {
  var link = document.createElement('link');
  link.rel = 'icon';
  link.type = 'image/png';
  link.href = '/w/images/Favicon.png';
  document.head.appendChild(link);
})();

/* Hero search bar above the page title */
(function gtHeroSearch() {
  function build() {
    var wrapper = document.createElement('div');
    wrapper.id = 'gt-hero-search';

    var form = document.createElement('form');
    form.action = '/wiki/Special:Search';
    form.method = 'get';
    form.setAttribute('role', 'search');
    form.setAttribute('aria-label', 'Search Grid Tactics Wiki');

    var label = document.createElement('label');
    label.setAttribute('for', 'gt-main-search');
    label.style.cssText = 'position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);';
    label.textContent = 'Search Grid Tactics Wiki';

    var input = document.createElement('input');
    input.type = 'search';
    input.name = 'search';
    input.id = 'gt-main-search';
    input.placeholder = 'Search cards, keywords, elements, rules\\u2026';
    input.autocomplete = 'off';
    input.spellcheck = false;

    var btn = document.createElement('button');
    btn.type = 'submit';
    btn.textContent = 'Search';

    form.appendChild(label);
    form.appendChild(input);
    form.appendChild(btn);
    wrapper.appendChild(form);
    return wrapper;
  }

  function tryInject() {
    if (document.getElementById('gt-hero-search')) return true;
    /* Insert BEFORE <main> to get a full-width row above the page title.
       (Citizen skin uses flex inside <main>, so siblings would sit beside the title.) */
    var main = document.getElementById('content')
      || document.querySelector('main.mw-body')
      || document.querySelector('main');
    if (main && main.parentNode) {
      main.parentNode.insertBefore(build(), main);
      return true;
    }
    return false;
  }

  /* Try immediately, then poll for the header (it appears as the body parses) */
  if (!tryInject()) {
    var poll = setInterval(function() {
      if (tryInject()) clearInterval(poll);
    }, 30);
    /* Fallback: stop polling after 5s */
    setTimeout(function() { clearInterval(poll); }, 5000);
  }
})();
"""


def push_vintage_common_js(site, dry_run: bool = False) -> str:
    """Replace MediaWiki:Common.js wholesale (fonts + favicon + hero search).

    Returns ``"created"``, ``"updated"``, or ``"unchanged"``.
    """
    page = site.pages["MediaWiki:Common.js"]
    current = page.text() if page.exists else ""

    if current.rstrip() == COMPOSED_COMMON_JS.rstrip():
        print("  MediaWiki:Common.js: unchanged (vintage JS current)")
        return "unchanged"

    if dry_run:
        verb = "would-update" if page.exists else "would-create"
        print(f"  MediaWiki:Common.js: {verb} (vintage JS, wholesale)")
        return verb

    page.edit(
        COMPOSED_COMMON_JS,
        summary="re-skin wiki JS payload (Alegreya fonts + favicon + hero search)",
    )
    verb = "updated" if current else "created"
    print(f"  MediaWiki:Common.js: {verb} (vintage JS, wholesale)")
    return verb


# ---------------------------------------------------------------------------
# Logo generation
# ---------------------------------------------------------------------------


def generate_logo_png(output_path: str | Path) -> Path:
    """Generate a 135x135 PNG logo with 'GT' text.

    Uses Pillow if available, otherwise creates a minimal placeholder PNG.
    Returns the output path.
    """
    output_path = Path(output_path)
    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGBA", (135, 135), (25, 18, 7, 255))
        draw = ImageDraw.Draw(img)

        # Draw border (bronze)
        draw.rectangle([2, 2, 132, 132], outline=(107, 87, 48, 255), width=2)

        # Draw "GT" text centered (parchment)
        try:
            font = ImageFont.truetype("arial.ttf", 52)
        except (OSError, IOError):
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 52)
            except (OSError, IOError):
                font = ImageFont.load_default()

        bbox = draw.textbbox((0, 0), "GT", font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
        x = (135 - text_w) // 2
        y = (135 - text_h) // 2 - bbox[1]
        draw.text((x, y), "GT", fill=(242, 234, 210, 255), font=font)

        img.save(str(output_path), "PNG")
    except ImportError:
        print("  WARNING: Pillow not available, creating placeholder logo")
        _write_minimal_png(output_path, 135, 135)

    return output_path


def generate_favicon_ico(output_path: str | Path) -> Path:
    """Generate a 32x32 ICO favicon with 'GT' text.

    Uses Pillow if available, otherwise creates a minimal valid ICO.
    Returns the output path.
    """
    output_path = Path(output_path)
    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGBA", (32, 32), (25, 18, 7, 255))
        draw = ImageDraw.Draw(img)

        # Draw border (bronze)
        draw.rectangle([1, 1, 30, 30], outline=(107, 87, 48, 255), width=1)

        # Draw "GT" text centered (parchment)
        try:
            font = ImageFont.truetype("arial.ttf", 16)
        except (OSError, IOError):
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 16)
            except (OSError, IOError):
                font = ImageFont.load_default()

        bbox = draw.textbbox((0, 0), "GT", font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
        x = (32 - text_w) // 2
        y = (32 - text_h) // 2 - bbox[1]
        draw.text((x, y), "GT", fill=(242, 234, 210, 255), font=font)

        img.save(str(output_path), format="ICO", sizes=[(32, 32)])
    except ImportError:
        print("  WARNING: Pillow not available, creating minimal favicon")
        _write_minimal_ico(output_path)

    return output_path


def generate_favicon_png(output_path: str | Path) -> Path:
    """Generate a 32x32 PNG favicon with 'GT' text.

    PNG fallback for MediaWiki instances that ban ICO uploads.
    Returns the output path.
    """
    output_path = Path(output_path)
    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGBA", (32, 32), (25, 18, 7, 255))
        draw = ImageDraw.Draw(img)

        draw.rectangle([1, 1, 30, 30], outline=(107, 87, 48, 255), width=1)

        try:
            font = ImageFont.truetype("arial.ttf", 16)
        except (OSError, IOError):
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 16)
            except (OSError, IOError):
                font = ImageFont.load_default()

        bbox = draw.textbbox((0, 0), "GT", font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
        x = (32 - text_w) // 2
        y = (32 - text_h) // 2 - bbox[1]
        draw.text((x, y), "GT", fill=(242, 234, 210, 255), font=font)

        img.save(str(output_path), "PNG")
    except ImportError:
        print("  WARNING: Pillow not available, creating placeholder favicon PNG")
        _write_minimal_png(output_path, 32, 32)

    return output_path


def _write_minimal_png(path: Path, width: int, height: int) -> None:
    """Write a minimal valid 1-pixel transparent PNG (fallback)."""
    import zlib

    def _chunk(chunk_type: bytes, data: bytes) -> bytes:
        c = chunk_type + data
        crc = struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)
        return struct.pack(">I", len(data)) + c + crc

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    # Single dark-brown pixel row, repeated
    raw_row = b"\x00" + b"\x19\x12\x07\xff" * width
    raw = raw_row * height
    idat_data = zlib.compress(raw)

    with open(path, "wb") as f:
        f.write(sig)
        f.write(_chunk(b"IHDR", ihdr_data))
        f.write(_chunk(b"IDAT", idat_data))
        f.write(_chunk(b"IEND", b""))


def _write_minimal_ico(path: Path) -> None:
    """Write a minimal valid 32x32 ICO file (fallback)."""
    # Create a minimal BMP-in-ICO
    size = 32
    # Generate raw BGRA pixel data (dark brown)
    pixels = b"\x07\x12\x19\xff" * (size * size)
    # AND mask (1bpp, all zeros = fully opaque)
    and_mask = b"\x00" * (size * size // 8)

    # BMP info header (40 bytes)
    bmp_header = struct.pack(
        "<IiiHHIIiiII",
        40,             # header size
        size,           # width
        size * 2,       # height (doubled for ICO)
        1,              # planes
        32,             # bpp
        0,              # compression
        len(pixels) + len(and_mask),  # image size
        0, 0,           # ppm x, y
        0, 0,           # colors used, important
    )

    image_data = bmp_header + pixels + and_mask
    # ICO header
    ico_header = struct.pack("<HHH", 0, 1, 1)  # reserved, type=ICO, count=1
    # ICO directory entry
    ico_entry = struct.pack(
        "<BBBBHHII",
        size,           # width
        size,           # height
        0,              # color palette
        0,              # reserved
        1,              # planes
        32,             # bpp
        len(image_data),  # size
        len(ico_header) + 16,  # offset (header + 1 entry)
    )

    with open(path, "wb") as f:
        f.write(ico_header)
        f.write(ico_entry)
        f.write(image_data)


# ---------------------------------------------------------------------------
# Logo / favicon upload
# ---------------------------------------------------------------------------


def upload_logo(site, dry_run: bool = False) -> str:
    """Generate and upload the site logo as File:Wiki.png.

    Returns status string.
    """
    if dry_run:
        print("  Logo: would-upload File:Wiki.png")
        return "would-upload"

    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        generate_logo_png(tmp_path)
        with open(tmp_path, "rb") as f:
            site.upload(
                file=f,
                filename="Wiki.png",
                description="Grid Tactics Wiki logo (135x135)",
                ignore=True,
                comment="upload site logo",
            )
        print("  Logo: uploaded File:Wiki.png")
        return "uploaded"
    except Exception as exc:
        exc_str = str(exc)
        if "fileexists-no-change" in exc_str or "duplicate" in exc_str.lower():
            print("  Logo: unchanged (already exists)")
            return "unchanged"
        print(f"  Logo: error - {exc}")
        return "error"
    finally:
        tmp_path.unlink(missing_ok=True)


def upload_favicon(site, dry_run: bool = False) -> str:
    """Generate and upload the favicon as File:Favicon.png.

    Uses PNG format because MediaWiki instances commonly ban ICO uploads.
    Returns status string.
    """
    if dry_run:
        print("  Favicon: would-upload File:Favicon.png")
        return "would-upload"

    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        generate_favicon_png(tmp_path)
        with open(tmp_path, "rb") as f:
            site.upload(
                file=f,
                filename="Favicon.png",
                description="Grid Tactics Wiki favicon (32x32)",
                ignore=True,
                comment="upload site favicon",
            )
        print("  Favicon: uploaded File:Favicon.png")
        return "uploaded"
    except Exception as exc:
        exc_str = str(exc)
        if "fileexists-no-change" in exc_str or "duplicate" in exc_str.lower():
            print("  Favicon: unchanged (already exists)")
            return "unchanged"
        print(f"  Favicon: error - {exc}")
        return "error"
    finally:
        tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Search verification
# ---------------------------------------------------------------------------


def verify_search(site) -> bool:
    """Verify MediaWiki search returns expected results.

    Checks:
    - Searching 'Rat' returns Rat-tribe cards
    - Searching 'Ranged' returns cards with that keyword

    Returns True if both checks pass.
    """
    all_pass = True

    # Search for "Rat"
    print("  Searching for 'Rat'...")
    try:
        result = site.api("query", list="search", srsearch="Rat", srlimit=20)
        hits = result.get("query", {}).get("search", [])
        titles = [h["title"] for h in hits]
        print(f"    Found {len(hits)} results: {', '.join(titles[:10])}")

        # Check that at least one Rat-tribe card appears
        rat_cards = [t for t in titles if "Rat" in t]
        if rat_cards:
            print(f"    OK: Rat-tribe cards found: {', '.join(rat_cards[:5])}")
        else:
            print("    WARN: No Rat-related cards in search results")
            all_pass = False
    except Exception as exc:
        print(f"    ERROR: search failed: {exc}")
        all_pass = False

    # Search for "Ranged" (use srwhat=text for full-text search of page content)
    print("  Searching for 'Ranged'...")
    try:
        result = site.api(
            "query", list="search", srsearch="Ranged",
            srlimit=20, srwhat="text",
        )
        hits = result.get("query", {}).get("search", [])
        titles = [h["title"] for h in hits]
        print(f"    Found {len(hits)} results: {', '.join(titles[:10])}")

        if hits:
            print(f"    OK: Ranged keyword cards found")
        else:
            print("    WARN: No results for 'Ranged' search")
            all_pass = False
    except Exception as exc:
        print(f"    ERROR: search failed: {exc}")
        all_pass = False

    return all_pass
