"""
CLI entry point for syncing card pages and art to the Grid Tactics Wiki.

Orchestrates card page upsert, art upload, and verification against the
live Railway wiki.  All card data comes from ``data/cards/*.json``; wikitext
is generated by :mod:`sync.sync_cards`.

Usage::

    cd wiki
    python -m sync.sync_wiki --all-cards         # Upsert all cards + upload art
    python -m sync.sync_wiki --card ratchanter    # Upsert single card by card_id
    python -m sync.sync_wiki --all-cards --dry-run  # Show what would change
    python -m sync.sync_wiki --verify             # Check Category:Card count
    python -m sync.sync_wiki --upload-art         # Upload art PNGs only
    python -m sync.sync_wiki --verify-deep        # Full verification suite
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from sync.client import MissingCredentialsError, get_site
from sync.sync_cards import build_card_name_map, card_to_wikitext

# ---------------------------------------------------------------------------
# Repo layout
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_CARDS_DIR = _REPO_ROOT / "data" / "cards"
_ART_DIR = _REPO_ROOT / "src" / "grid_tactics" / "server" / "static" / "art"
_WIKI_DIR = Path(__file__).resolve().parent.parent
_RESUME_PATH = _WIKI_DIR / ".sync_resume.json"

# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------


def load_all_cards(cards_dir: Path) -> list[dict]:
    """Load all card JSONs from *cards_dir*, sorted by card_id."""
    cards: list[dict] = []
    for path in sorted(cards_dir.glob("*.json")):
        try:
            card = json.loads(path.read_text(encoding="utf-8"))
            cards.append(card)
        except (json.JSONDecodeError, KeyError) as exc:
            print(f"  warning: skipping {path.name}: {exc}")
    cards.sort(key=lambda c: c.get("card_id", ""))
    return cards


def upsert_card_page(
    site,
    card: dict,
    name_map: dict[str, str],
    art_dir: Path,
    dry_run: bool = False,
) -> dict:
    """Upsert a single card page on the wiki.

    Returns dict with card_id, page title, and status.
    """
    card_id = card.get("card_id", "")
    card_name = card.get("name", "")
    art_exists = (art_dir / f"{card_id}.png").exists()
    wikitext = card_to_wikitext(card, name_map, art_exists=art_exists)
    page_title = f"Card:{card_name}"

    if dry_run:
        page = site.pages[page_title]
        if not page.exists:
            return {"card_id": card_id, "page": page_title, "status": "would-create"}
        current = page.text()
        if current.rstrip() == wikitext.rstrip():
            return {"card_id": card_id, "page": page_title, "status": "unchanged"}
        return {"card_id": card_id, "page": page_title, "status": "would-update"}

    page = site.pages[page_title]
    summary = f"sync {card_name} from data/cards/{card_id}.json"

    if not page.exists:
        page.edit(wikitext, summary=summary)
        return {"card_id": card_id, "page": page_title, "status": "created"}

    current = page.text()
    if current.rstrip() == wikitext.rstrip():
        return {"card_id": card_id, "page": page_title, "status": "unchanged"}

    page.edit(wikitext, summary=summary)
    return {"card_id": card_id, "page": page_title, "status": "updated"}


def upload_card_art(
    site,
    card_id: str,
    card_name: str,
    art_dir: Path,
    dry_run: bool = False,
) -> str:
    """Upload card art PNG to the wiki.  Returns status string."""
    art_path = art_dir / f"{card_id}.png"
    if not art_path.exists():
        return "no-art"
    if dry_run:
        return "dry-run"
    try:
        with open(art_path, "rb") as f:
            site.upload(
                file=f,
                filename=f"{card_id}.png",
                description=f"Card art for [[Card:{card_name}]].",
                ignore=True,
                comment="sync card art",
            )
        return "uploaded"
    except Exception as exc:
        # MediaWiki returns fileexists-no-change for exact duplicate uploads.
        # Treat as "unchanged" for idempotency.
        exc_str = str(exc)
        if "fileexists-no-change" in exc_str or "duplicate" in exc_str.lower():
            return "unchanged"
        print(f"  art upload error ({card_id}): {exc}")
        return "error"


def verify_card_count(site, expected: int) -> bool:
    """Check that Category:Card has the expected number of members."""
    try:
        cat = site.categories["Card"]
        actual = sum(1 for _ in cat)
    except Exception as exc:
        print(f"  error reading Category:Card: {exc}")
        return False
    print(f"  Category:Card: {actual} pages (expected {expected})")
    return actual == expected


# ---------------------------------------------------------------------------
# Deep verification
# ---------------------------------------------------------------------------


def _verify_cross_links(site) -> tuple[int, int]:
    """Check that key cross-link target pages exist.  Returns (pass, fail)."""
    targets = [
        "Card:Common Rat",
        "Card:Red Diodebot",
        "Card:Blue Diodebot",
        "Card:Green Diodebot",
        "Card:Pyre Archer",
        "Card:Grave Caller",
        "Card:Fallen Paladin",
    ]
    ok = fail = 0
    for title in targets:
        page = site.pages[title]
        if page.exists:
            ok += 1
            print(f"    OK  {title}")
        else:
            fail += 1
            print(f"    MISSING  {title}")
    return ok, fail


def _smw_val(v):
    """Extract a scalar from an SMW printout value (may be dict or number)."""
    if isinstance(v, dict):
        return v.get("fulltext", v)
    return v


def _verify_smw_properties(site) -> tuple[int, int]:
    """Run an #ask query and spot-check a few card properties."""
    query = "[[Category:Card]]|?Name|?CardType|?Element|?Cost|?Attack|?HP|limit=50"
    print(f"    Query: {query}")
    results = list(site.ask(query))
    count = len(results)
    print(f"    Results: {count} cards returned")
    if count < 30:
        print(
            f"    WARNING: only {count} results (expected >=30). "
            "SMW job queue may need time. Consider running maintenance/runJobs.php."
        )

    # Spot checks
    checks_ok = checks_fail = 0
    spot_checks = {
        "Card:Ratchanter": {"Cost": 4, "Attack": 15, "HP": 30},
        "Card:Counter Spell": {"Cost": 2},
        "Card:Fireball": {"Cost": 3},
    }

    # Build lookup by fulltext
    result_map: dict[str, dict] = {}
    for r in results:
        ft = r.get("fulltext", "") if isinstance(r, dict) else ""
        if ft:
            result_map[ft] = r

    for title, expected in spot_checks.items():
        r = result_map.get(title)
        if not r:
            print(f"    FAIL  {title} not in results")
            checks_fail += 1
            continue
        printouts = r.get("printouts", {})
        all_ok = True
        for prop, exp_val in expected.items():
            vals = printouts.get(prop, [])
            if vals:
                actual = float(_smw_val(vals[0]))
                if actual != float(exp_val):
                    print(f"    FAIL  {title}.{prop}: expected {exp_val}, got {actual}")
                    all_ok = False
            else:
                print(f"    FAIL  {title}.{prop}: no value returned")
                all_ok = False
        if all_ok:
            print(f"    OK  {title}: {expected}")
            checks_ok += 1
        else:
            checks_fail += 1

    return checks_ok, checks_fail


def _verify_art_files(site) -> tuple[int, int]:
    """Check that art files exist on the wiki for cards with local PNGs."""
    art_card_ids = [
        "ratchanter", "blue_diodebot", "emberplague_rat", "fallen_paladin",
        "furryroach", "giant_rat", "grave_caller", "green_diodebot",
        "pyre_archer", "rat", "rathopper", "reanimated_bones",
        "red_diodebot", "rgb_lasercannon", "surgefed_sparkbot",
    ]
    ok = fail = 0
    for card_id in art_card_ids:
        filename = f"{card_id}.png"
        img = site.images[filename]
        if img.exists:
            ok += 1
            print(f"    OK  File:{filename}")
        else:
            fail += 1
            print(f"    MISSING  File:{filename}")
    return ok, fail


def verify_deep(site, expected_count: int) -> bool:
    """Run full verification suite: category count, cross-links, SMW, art."""
    all_pass = True

    print("\n[1/4] Category count")
    if not verify_card_count(site, expected_count):
        all_pass = False

    print("\n[2/4] Cross-link targets")
    ok, fail = _verify_cross_links(site)
    print(f"  Cross-links: {ok} OK, {fail} missing")
    if fail > 0:
        all_pass = False

    print("\n[3/4] SMW properties")
    ok, fail = _verify_smw_properties(site)
    print(f"  SMW spot-checks: {ok} OK, {fail} failed")
    if fail > 0:
        all_pass = False

    print("\n[4/4] Art files")
    ok, fail = _verify_art_files(site)
    print(f"  Art files: {ok} OK, {fail} missing")
    if fail > 0:
        all_pass = False

    return all_pass


# ---------------------------------------------------------------------------
# Template bootstrapping
# ---------------------------------------------------------------------------

_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"


def _bootstrap_deprecated_template(site) -> str:
    """Upsert Template:DeprecatedCard on the wiki (idempotent).

    Returns ``"created"``, ``"updated"``, or ``"unchanged"``.
    """
    template_path = _TEMPLATES_DIR / "DeprecatedCard.wiki"
    expected = template_path.read_text(encoding="utf-8")
    page = site.pages["Template:DeprecatedCard"]
    if page.exists:
        current = page.text()
        if current.rstrip() == expected.rstrip():
            return "unchanged"
        page.edit(expected, summary="update Template:DeprecatedCard")
        return "updated"
    page.edit(expected, summary="bootstrap Template:DeprecatedCard")
    return "created"


def _bootstrap_card_template(site) -> str:
    """Upsert Template:Card on the wiki (idempotent).

    Returns ``"created"``, ``"updated"``, or ``"unchanged"``.
    """
    template_path = _TEMPLATES_DIR / "Card.wiki"
    expected = template_path.read_text(encoding="utf-8")
    page = site.pages["Template:Card"]
    if page.exists:
        current = page.text()
        if current.rstrip() == expected.rstrip():
            return "unchanged"
        page.edit(expected, summary="update Template:Card (add LastChangedPatch)")
        return "updated"
    page.edit(expected, summary="bootstrap Template:Card")
    return "created"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync Grid Tactics card data to the wiki.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--all-cards", action="store_true",
        help="Upsert all card pages and upload art",
    )
    group.add_argument(
        "--card", type=str, metavar="CARD_ID",
        help="Upsert a single card by card_id",
    )
    group.add_argument(
        "--verify", action="store_true",
        help="Verify Category:Card count matches JSON count",
    )
    group.add_argument(
        "--upload-art", action="store_true",
        help="Upload art PNGs only (no page edits)",
    )
    group.add_argument(
        "--verify-deep", action="store_true",
        help="Full verification: category count, cross-links, SMW, art files",
    )
    group.add_argument(
        "--taxonomy", action="store_true",
        help="Sync element, tribe, keyword, and rules pages",
    )
    group.add_argument(
        "--verify-taxonomy", action="store_true",
        help="Verify all taxonomy pages (elements, tribes, keywords, rules)",
    )
    group.add_argument(
        "--homepage", action="store_true",
        help="Sync the Main Page (navigation hub)",
    )
    group.add_argument(
        "--patch", action="store_true",
        help="Sync pending patch notes to wiki",
    )
    group.add_argument(
        "--patch-commit", type=str, metavar="SHA",
        help="Sync a specific commit's patch notes",
    )
    group.add_argument(
        "--showcase", action="store_true",
        help="Sync the Semantic:Showcase query demonstration page",
    )
    group.add_argument(
        "--deckguide", action="store_true",
        help="Sync the Deck Building Guide page (strategy + auto archetypes)",
    )
    group.add_argument(
        "--polish", action="store_true",
        help="Push mobile CSS, logo, favicon, and configure branding",
    )
    group.add_argument(
        "--verify-search", action="store_true",
        help="Verify MediaWiki search returns expected card results",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would change without making edits",
    )
    parser.add_argument(
        "--no-resume", action="store_true",
        help="Ignore any existing resume manifest and do a full sync",
    )
    args = parser.parse_args(argv)

    # --homepage
    if args.homepage:
        from sync.sync_homepage import sync_main_page

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Syncing Main Page{dry_label}...")
        status = sync_main_page(site, dry_run=args.dry_run)
        print(f"Main Page: {status}")
        return 0

    # --showcase
    if args.showcase:
        from sync.sync_showcase import sync_showcase_page

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Syncing Semantic:Showcase{dry_label}...")
        status = sync_showcase_page(site, dry_run=args.dry_run)
        print(f"Semantic:Showcase: {status}")
        return 0

    # --deckguide
    if args.deckguide:
        from sync.sync_deckguide import sync_deckguide

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Syncing Deck Building Guide{dry_label}...")
        status = sync_deckguide(site, _CARDS_DIR, dry_run=args.dry_run)
        print(f"Deck Building Guide: {status}")
        return 0

    # --polish
    if args.polish:
        from sync.sync_polish import (
            configure_logo_and_favicon,
            push_mobile_css,
            upload_favicon,
            upload_logo,
        )

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Running launch polish{dry_label}...")

        print("\n=== Mobile CSS ===")
        css_status = push_mobile_css(site, dry_run=args.dry_run)

        print("\n=== Logo ===")
        logo_status = upload_logo(site, dry_run=args.dry_run)

        print("\n=== Favicon ===")
        fav_status = upload_favicon(site, dry_run=args.dry_run)

        print("\n=== Logo & Favicon Configuration ===")
        config_status = configure_logo_and_favicon(site, dry_run=args.dry_run)

        print(f"\nPolish complete: CSS={css_status}, Logo={logo_status}, "
              f"Favicon={fav_status}, Config={config_status}")
        return 0

    # --verify-search
    if args.verify_search:
        from sync.sync_polish import verify_search

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print("Verifying search...")
        ok = verify_search(site)
        print(f"\nSearch verification: {'PASS' if ok else 'FAIL'}")
        return 0 if ok else 1

    # --patch (no card loading needed)
    if args.patch:
        from sync.sync_patches import bootstrap_patch_template, sync_all_pending

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        # Bootstrap all templates needed for patch sync
        tmpl_status = bootstrap_patch_template(site)
        if tmpl_status != "unchanged":
            print(f"  Template:Patch: {tmpl_status}")
        dep_status = _bootstrap_deprecated_template(site)
        if dep_status != "unchanged":
            print(f"  Template:DeprecatedCard: {dep_status}")
        card_status = _bootstrap_card_template(site)
        if card_status != "unchanged":
            print(f"  Template:Card: {card_status}")
        results = sync_all_pending(site, _REPO_ROOT, args.dry_run)
        if not results:
            print("No pending patch changes.")
        else:
            for r in results:
                print(f"  {r.get('page', r.get('version', '?'))}: {r['status']}")
        return 0

    # --patch-commit SHA
    if args.patch_commit:
        import subprocess as _sp

        from sync.sync_patches import bootstrap_patch_template, sync_patch

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        tmpl_status = bootstrap_patch_template(site)
        if tmpl_status != "unchanged":
            print(f"  Template:Patch: {tmpl_status}")
        # Get parent of the specified commit
        result = _sp.run(
            ["git", "rev-parse", f"{args.patch_commit}^"],
            capture_output=True, text=True, cwd=str(_REPO_ROOT),
        )
        if result.returncode != 0:
            print(f"ERROR: cannot find parent of {args.patch_commit}", file=sys.stderr)
            return 1
        parent = result.stdout.strip()
        r = sync_patch(site, _REPO_ROOT, parent, args.patch_commit, dry_run=args.dry_run)
        print(f"  {r.get('page', r.get('version', '?'))}: {r['status']}")
        return 0

    # Load cards
    cards = load_all_cards(_CARDS_DIR)
    name_map = build_card_name_map(_CARDS_DIR)
    card_count = len(cards)

    # --verify (no wiki connection needed for card count, but need site)
    if args.verify:
        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Verifying card count (expected {card_count})...")
        ok = verify_card_count(site, card_count)
        return 0 if ok else 1

    # --verify-deep
    if args.verify_deep:
        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Running deep verification (expected {card_count} cards)...")
        ok = verify_deep(site, card_count)
        print(f"\nOverall: {'PASS' if ok else 'FAIL'}")
        return 0 if ok else 1

    # --verify-taxonomy
    if args.verify_taxonomy:
        from sync.sync_taxonomy import verify_taxonomy

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2

        glossary_path = _REPO_ROOT / "data" / "GLOSSARY.md"
        print("Running taxonomy verification...")
        ok = verify_taxonomy(site, _CARDS_DIR, glossary_path)
        return 0 if ok else 1

    # --taxonomy
    if args.taxonomy:
        from sync.sync_taxonomy import (
            sync_elements, sync_tribes, sync_keywords, sync_rules_pages,
        )

        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2

        glossary_path = _REPO_ROOT / "data" / "GLOSSARY.md"
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Syncing taxonomy pages{dry_label}...")

        print("\n=== Elements ===")
        elem_counts = sync_elements(site, _CARDS_DIR, dry_run=args.dry_run)

        print("\n=== Tribes ===")
        tribe_counts = sync_tribes(site, _CARDS_DIR, dry_run=args.dry_run)

        print("\n=== Keywords ===")
        kw_counts = sync_keywords(site, glossary_path, dry_run=args.dry_run)

        print("\n=== Rules Pages ===")
        rules_counts = sync_rules_pages(site, dry_run=args.dry_run)

        # Summary
        all_counts = [elem_counts, tribe_counts, kw_counts, rules_counts]
        total_created = sum(c["created"] for c in all_counts)
        total_updated = sum(c["updated"] for c in all_counts)
        total_unchanged = sum(c["unchanged"] for c in all_counts)
        total = total_created + total_updated + total_unchanged
        print(f"\nTaxonomy sync complete: {total} pages "
              f"({total_created} created, {total_updated} updated, "
              f"{total_unchanged} unchanged)")
        print(f"  Elements: {sum(elem_counts.values())}, "
              f"Tribes: {sum(tribe_counts.values())}, "
              f"Keywords: {sum(kw_counts.values())}, "
              f"Rules: {sum(rules_counts.values())}")

        return 0

    # Connect to wiki for edit operations
    try:
        site = get_site()
    except MissingCredentialsError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    # --upload-art
    if args.upload_art:
        print(f"Uploading art for {card_count} cards...")
        counts = {"uploaded": 0, "no-art": 0, "dry-run": 0, "unchanged": 0, "error": 0}
        for card in cards:
            card_id = card.get("card_id", "")
            card_name = card.get("name", "")
            status = upload_card_art(site, card_id, card_name, _ART_DIR, args.dry_run)
            counts[status] = counts.get(status, 0) + 1
            if status != "no-art":
                print(f"  {card_id}: {status}")
        print(f"\nArt: {counts['uploaded']} uploaded, {counts['no-art']} no-art, "
              f"{counts.get('error', 0)} errors.")
        return 0

    # --card CARD_ID
    if args.card:
        target_id = args.card
        card = next((c for c in cards if c.get("card_id") == target_id), None)
        if card is None:
            print(f"ERROR: card_id '{target_id}' not found in {_CARDS_DIR}",
                  file=sys.stderr)
            return 2
        result = upsert_card_page(site, card, name_map, _ART_DIR, args.dry_run)
        print(f"  {result['page']}: {result['status']}")
        art_status = upload_card_art(
            site, target_id, card.get("name", ""), _ART_DIR, args.dry_run,
        )
        if art_status != "no-art":
            print(f"  art: {art_status}")
        return 0

    # --all-cards
    if args.all_cards:
        dry_label = " (dry run)" if args.dry_run else ""

        # --- Resume manifest handling ---
        resuming = False
        completed_ids: list[str] = []

        if args.no_resume and _RESUME_PATH.exists():
            _RESUME_PATH.unlink()
            print("Deleted existing resume manifest (--no-resume).")

        if not args.no_resume and _RESUME_PATH.exists():
            try:
                manifest = json.loads(_RESUME_PATH.read_text(encoding="utf-8"))
                remaining_ids = set(manifest.get("remaining_card_ids", []))
                completed_ids = manifest.get("completed_card_ids", [])
                prev_count = len(completed_ids)
                cards = [c for c in cards if c.get("card_id", "") in remaining_ids]
                card_count = len(cards)
                resuming = True
                print(f"Resuming from manifest: {card_count} remaining cards "
                      f"({prev_count} previously completed).")
            except (json.JSONDecodeError, KeyError) as exc:
                print(f"Warning: corrupt resume manifest, starting fresh: {exc}")
                _RESUME_PATH.unlink(missing_ok=True)

        print(f"Syncing {card_count} cards to wiki{dry_label}...")

        page_counts = {"created": 0, "updated": 0, "unchanged": 0,
                       "would-create": 0, "would-update": 0, "error": 0}
        art_counts = {"uploaded": 0, "no-art": 0, "dry-run": 0, "unchanged": 0, "error": 0}

        all_card_ids = [c.get("card_id", "") for c in cards]
        started_at = datetime.now(timezone.utc).isoformat()

        try:
            for i, card in enumerate(cards):
                card_id = card.get("card_id", "")
                card_name = card.get("name", "")
                # Upsert page
                try:
                    result = upsert_card_page(site, card, name_map, _ART_DIR, args.dry_run)
                    status = result["status"]
                    page_counts[status] = page_counts.get(status, 0) + 1
                    print(f"  {result['page']}: {status}")
                except Exception as exc:
                    page_counts["error"] += 1
                    print(f"  Card:{card_name}: ERROR - {exc}")
                    completed_ids.append(card_id)
                    continue

                # Upload art
                art_status = upload_card_art(
                    site, card_id, card_name, _ART_DIR, args.dry_run,
                )
                art_counts[art_status] = art_counts.get(art_status, 0) + 1

                completed_ids.append(card_id)

        except KeyboardInterrupt:
            raise
        except Exception as exc:
            # Batch-level failure: write resume manifest
            remaining = all_card_ids[i:]  # noqa: F821 — i is defined from the loop
            manifest = {
                "command": "all-cards",
                "started_at": started_at,
                "failed_at": datetime.now(timezone.utc).isoformat(),
                "completed_card_ids": completed_ids,
                "remaining_card_ids": remaining,
                "dry_run": args.dry_run,
            }
            _RESUME_PATH.write_text(
                json.dumps(manifest, indent=2), encoding="utf-8",
            )
            total = len(completed_ids) + len(remaining)
            print(f"\nBATCH FAILED after {len(completed_ids)}/{total} cards. "
                  f"Resume manifest written to .sync_resume.json. "
                  f"Rerun --all-cards to continue.")
            print(f"Error: {exc}")
            return 1

        # Successful completion: delete resume manifest if it exists
        _RESUME_PATH.unlink(missing_ok=True)

        # Summary
        print(f"\nSynced {card_count} cards: "
              f"{page_counts['created']} created, "
              f"{page_counts['updated']} updated, "
              f"{page_counts['unchanged']} unchanged"
              f"{', ' + str(page_counts['would-create']) + ' would-create' if page_counts.get('would-create') else ''}"
              f"{', ' + str(page_counts['would-update']) + ' would-update' if page_counts.get('would-update') else ''}"
              f"{', ' + str(page_counts['error']) + ' errors' if page_counts.get('error') else ''}"
              f". Art: {art_counts['uploaded']} uploaded"
              f", {art_counts['no-art']} no-art"
              f"{', ' + str(art_counts.get('dry-run', 0)) + ' dry-run' if art_counts.get('dry-run') else ''}"
              f"{', ' + str(art_counts.get('error', 0)) + ' errors' if art_counts.get('error') else ''}"
              f".")
        return 1 if page_counts["error"] > 0 else 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
