"""
CLI entry point for syncing card pages and art to the Grid Tactics Wiki.

Orchestrates card page upsert, art upload, and verification against the
live Railway wiki.  All card data comes from ``data/cards/*.json``; wikitext
is generated by :mod:`sync.sync_cards`.

Usage::

    cd wiki
    python -m sync.sync_wiki --all-cards         # Upsert all cards + upload art
    python -m sync.sync_wiki --card ratchanter    # Upsert single card by card_id
    python -m sync.sync_wiki --all-cards --dry-run  # Show what would change
    python -m sync.sync_wiki --verify             # Check Category:Card count
    python -m sync.sync_wiki --upload-art         # Upload art PNGs only
    python -m sync.sync_wiki --verify-deep        # Full verification suite
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from sync.client import MissingCredentialsError, get_site
from sync.sync_cards import build_card_name_map, card_to_wikitext

# ---------------------------------------------------------------------------
# Repo layout
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_CARDS_DIR = _REPO_ROOT / "data" / "cards"
_ART_DIR = _REPO_ROOT / "src" / "grid_tactics" / "server" / "static" / "art"

# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------


def load_all_cards(cards_dir: Path) -> list[dict]:
    """Load all card JSONs from *cards_dir*, sorted by card_id."""
    cards: list[dict] = []
    for path in sorted(cards_dir.glob("*.json")):
        try:
            card = json.loads(path.read_text(encoding="utf-8"))
            cards.append(card)
        except (json.JSONDecodeError, KeyError) as exc:
            print(f"  warning: skipping {path.name}: {exc}")
    cards.sort(key=lambda c: c.get("card_id", ""))
    return cards


def upsert_card_page(
    site,
    card: dict,
    name_map: dict[str, str],
    art_dir: Path,
    dry_run: bool = False,
) -> dict:
    """Upsert a single card page on the wiki.

    Returns dict with card_id, page title, and status.
    """
    card_id = card.get("card_id", "")
    card_name = card.get("name", "")
    art_exists = (art_dir / f"{card_id}.png").exists()
    wikitext = card_to_wikitext(card, name_map, art_exists=art_exists)
    page_title = f"Card:{card_name}"

    if dry_run:
        page = site.pages[page_title]
        if not page.exists:
            return {"card_id": card_id, "page": page_title, "status": "would-create"}
        current = page.text()
        if current.rstrip() == wikitext.rstrip():
            return {"card_id": card_id, "page": page_title, "status": "unchanged"}
        return {"card_id": card_id, "page": page_title, "status": "would-update"}

    page = site.pages[page_title]
    summary = f"sync {card_name} from data/cards/{card_id}.json"

    if not page.exists:
        page.edit(wikitext, summary=summary)
        return {"card_id": card_id, "page": page_title, "status": "created"}

    current = page.text()
    if current.rstrip() == wikitext.rstrip():
        return {"card_id": card_id, "page": page_title, "status": "unchanged"}

    page.edit(wikitext, summary=summary)
    return {"card_id": card_id, "page": page_title, "status": "updated"}


def upload_card_art(
    site,
    card_id: str,
    card_name: str,
    art_dir: Path,
    dry_run: bool = False,
) -> str:
    """Upload card art PNG to the wiki.  Returns status string."""
    art_path = art_dir / f"{card_id}.png"
    if not art_path.exists():
        return "no-art"
    if dry_run:
        return "dry-run"
    try:
        with open(art_path, "rb") as f:
            site.upload(
                file=f,
                filename=f"{card_id}.png",
                description=f"Card art for [[Card:{card_name}]].",
                ignore=True,
                comment="sync card art",
            )
        return "uploaded"
    except Exception as exc:
        # MediaWiki returns fileexists-no-change for exact duplicate uploads.
        # Treat as "unchanged" for idempotency.
        exc_str = str(exc)
        if "fileexists-no-change" in exc_str or "duplicate" in exc_str.lower():
            return "unchanged"
        print(f"  art upload error ({card_id}): {exc}")
        return "error"


def verify_card_count(site, expected: int) -> bool:
    """Check that Category:Card has the expected number of members."""
    try:
        cat = site.categories["Card"]
        actual = sum(1 for _ in cat)
    except Exception as exc:
        print(f"  error reading Category:Card: {exc}")
        return False
    print(f"  Category:Card: {actual} pages (expected {expected})")
    return actual == expected


# ---------------------------------------------------------------------------
# Deep verification
# ---------------------------------------------------------------------------


def _verify_cross_links(site) -> tuple[int, int]:
    """Check that key cross-link target pages exist.  Returns (pass, fail)."""
    targets = [
        "Card:Common Rat",
        "Card:Red Diodebot",
        "Card:Blue Diodebot",
        "Card:Green Diodebot",
        "Card:Pyre Archer",
        "Card:Grave Caller",
        "Card:Fallen Paladin",
    ]
    ok = fail = 0
    for title in targets:
        page = site.pages[title]
        if page.exists:
            ok += 1
            print(f"    OK  {title}")
        else:
            fail += 1
            print(f"    MISSING  {title}")
    return ok, fail


def _smw_val(v):
    """Extract a scalar from an SMW printout value (may be dict or number)."""
    if isinstance(v, dict):
        return v.get("fulltext", v)
    return v


def _verify_smw_properties(site) -> tuple[int, int]:
    """Run an #ask query and spot-check a few card properties."""
    query = "[[Category:Card]]|?Name|?CardType|?Element|?Cost|?Attack|?HP|limit=50"
    print(f"    Query: {query}")
    results = list(site.ask(query))
    count = len(results)
    print(f"    Results: {count} cards returned")
    if count < 30:
        print(
            f"    WARNING: only {count} results (expected >=30). "
            "SMW job queue may need time. Consider running maintenance/runJobs.php."
        )

    # Spot checks
    checks_ok = checks_fail = 0
    spot_checks = {
        "Card:Ratchanter": {"Cost": 4, "Attack": 15, "HP": 30},
        "Card:Counter Spell": {"Cost": 2},
        "Card:Fireball": {"Cost": 3},
    }

    # Build lookup by fulltext
    result_map: dict[str, dict] = {}
    for r in results:
        ft = r.get("fulltext", "") if isinstance(r, dict) else ""
        if ft:
            result_map[ft] = r

    for title, expected in spot_checks.items():
        r = result_map.get(title)
        if not r:
            print(f"    FAIL  {title} not in results")
            checks_fail += 1
            continue
        printouts = r.get("printouts", {})
        all_ok = True
        for prop, exp_val in expected.items():
            vals = printouts.get(prop, [])
            if vals:
                actual = float(_smw_val(vals[0]))
                if actual != float(exp_val):
                    print(f"    FAIL  {title}.{prop}: expected {exp_val}, got {actual}")
                    all_ok = False
            else:
                print(f"    FAIL  {title}.{prop}: no value returned")
                all_ok = False
        if all_ok:
            print(f"    OK  {title}: {expected}")
            checks_ok += 1
        else:
            checks_fail += 1

    return checks_ok, checks_fail


def _verify_art_files(site) -> tuple[int, int]:
    """Check that art files exist on the wiki for cards with local PNGs."""
    art_card_ids = [
        "ratchanter", "blue_diodebot", "emberplague_rat", "fallen_paladin",
        "furryroach", "giant_rat", "grave_caller", "green_diodebot",
        "pyre_archer", "rat", "rathopper", "reanimated_bones",
        "red_diodebot", "rgb_lasercannon", "surgefed_sparkbot",
    ]
    ok = fail = 0
    for card_id in art_card_ids:
        filename = f"{card_id}.png"
        img = site.images[filename]
        if img.exists:
            ok += 1
            print(f"    OK  File:{filename}")
        else:
            fail += 1
            print(f"    MISSING  File:{filename}")
    return ok, fail


def verify_deep(site, expected_count: int) -> bool:
    """Run full verification suite: category count, cross-links, SMW, art."""
    all_pass = True

    print("\n[1/4] Category count")
    if not verify_card_count(site, expected_count):
        all_pass = False

    print("\n[2/4] Cross-link targets")
    ok, fail = _verify_cross_links(site)
    print(f"  Cross-links: {ok} OK, {fail} missing")
    if fail > 0:
        all_pass = False

    print("\n[3/4] SMW properties")
    ok, fail = _verify_smw_properties(site)
    print(f"  SMW spot-checks: {ok} OK, {fail} failed")
    if fail > 0:
        all_pass = False

    print("\n[4/4] Art files")
    ok, fail = _verify_art_files(site)
    print(f"  Art files: {ok} OK, {fail} missing")
    if fail > 0:
        all_pass = False

    return all_pass


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync Grid Tactics card data to the wiki.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--all-cards", action="store_true",
        help="Upsert all card pages and upload art",
    )
    group.add_argument(
        "--card", type=str, metavar="CARD_ID",
        help="Upsert a single card by card_id",
    )
    group.add_argument(
        "--verify", action="store_true",
        help="Verify Category:Card count matches JSON count",
    )
    group.add_argument(
        "--upload-art", action="store_true",
        help="Upload art PNGs only (no page edits)",
    )
    group.add_argument(
        "--verify-deep", action="store_true",
        help="Full verification: category count, cross-links, SMW, art files",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would change without making edits",
    )
    args = parser.parse_args(argv)

    # Load cards
    cards = load_all_cards(_CARDS_DIR)
    name_map = build_card_name_map(_CARDS_DIR)
    card_count = len(cards)

    # --verify (no wiki connection needed for card count, but need site)
    if args.verify:
        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Verifying card count (expected {card_count})...")
        ok = verify_card_count(site, card_count)
        return 0 if ok else 1

    # --verify-deep
    if args.verify_deep:
        try:
            site = get_site()
        except MissingCredentialsError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Running deep verification (expected {card_count} cards)...")
        ok = verify_deep(site, card_count)
        print(f"\nOverall: {'PASS' if ok else 'FAIL'}")
        return 0 if ok else 1

    # Connect to wiki for edit operations
    try:
        site = get_site()
    except MissingCredentialsError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    # --upload-art
    if args.upload_art:
        print(f"Uploading art for {card_count} cards...")
        counts = {"uploaded": 0, "no-art": 0, "dry-run": 0, "unchanged": 0, "error": 0}
        for card in cards:
            card_id = card.get("card_id", "")
            card_name = card.get("name", "")
            status = upload_card_art(site, card_id, card_name, _ART_DIR, args.dry_run)
            counts[status] = counts.get(status, 0) + 1
            if status != "no-art":
                print(f"  {card_id}: {status}")
        print(f"\nArt: {counts['uploaded']} uploaded, {counts['no-art']} no-art, "
              f"{counts.get('error', 0)} errors.")
        return 0

    # --card CARD_ID
    if args.card:
        target_id = args.card
        card = next((c for c in cards if c.get("card_id") == target_id), None)
        if card is None:
            print(f"ERROR: card_id '{target_id}' not found in {_CARDS_DIR}",
                  file=sys.stderr)
            return 2
        result = upsert_card_page(site, card, name_map, _ART_DIR, args.dry_run)
        print(f"  {result['page']}: {result['status']}")
        art_status = upload_card_art(
            site, target_id, card.get("name", ""), _ART_DIR, args.dry_run,
        )
        if art_status != "no-art":
            print(f"  art: {art_status}")
        return 0

    # --all-cards
    if args.all_cards:
        dry_label = " (dry run)" if args.dry_run else ""
        print(f"Syncing {card_count} cards to wiki{dry_label}...")

        page_counts = {"created": 0, "updated": 0, "unchanged": 0,
                       "would-create": 0, "would-update": 0, "error": 0}
        art_counts = {"uploaded": 0, "no-art": 0, "dry-run": 0, "unchanged": 0, "error": 0}

        for card in cards:
            card_id = card.get("card_id", "")
            card_name = card.get("name", "")
            # Upsert page
            try:
                result = upsert_card_page(site, card, name_map, _ART_DIR, args.dry_run)
                status = result["status"]
                page_counts[status] = page_counts.get(status, 0) + 1
                print(f"  {result['page']}: {status}")
            except Exception as exc:
                page_counts["error"] += 1
                print(f"  Card:{card_name}: ERROR - {exc}")
                continue

            # Upload art
            art_status = upload_card_art(
                site, card_id, card_name, _ART_DIR, args.dry_run,
            )
            art_counts[art_status] = art_counts.get(art_status, 0) + 1

        # Summary
        print(f"\nSynced {card_count} cards: "
              f"{page_counts['created']} created, "
              f"{page_counts['updated']} updated, "
              f"{page_counts['unchanged']} unchanged"
              f"{', ' + str(page_counts['would-create']) + ' would-create' if page_counts.get('would-create') else ''}"
              f"{', ' + str(page_counts['would-update']) + ' would-update' if page_counts.get('would-update') else ''}"
              f"{', ' + str(page_counts['error']) + ' errors' if page_counts.get('error') else ''}"
              f". Art: {art_counts['uploaded']} uploaded"
              f", {art_counts['no-art']} no-art"
              f"{', ' + str(art_counts.get('dry-run', 0)) + ' dry-run' if art_counts.get('dry-run') else ''}"
              f"{', ' + str(art_counts.get('error', 0)) + ' errors' if art_counts.get('error') else ''}"
              f".")
        return 1 if page_counts["error"] > 0 else 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
